image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - build
  - test

build_job:
  stage: build
  script:
    - dotnet build

test_job:
  stage: test
  script:
    - dotnet test --logger:nunit --results-directory:test_results
  artifacts:
    paths:
      - test_results
